#!/usr/bin/env groovy

pipeline {
    agent any
    stages {
        stage('First step') {
            steps {
                sh 'First step'
            }
        }
        stage('Second step') {
            steps {
                sh 'Second step'
            }
        }
    }
}